### PR TITLE
Docs update

### PR DESCRIPTION
**Pull request by zulh-civo**
This PR contains docs/Markdown files update for all Resources (Data Source docs update will be in different PR). Once this get merged and released, it will be reflected at https://registry.terraform.io/providers/civo/civo/latest/docs.

### CODE REVIEW

**Review by alejandrojnm — APPROVED** [review]

**Comment by zulh-civo** [comment]
@alejandrojnm - can you review this again?

@saiyam1814 - can you review this as well?

**Review by alejandrojnm — APPROVED** [review]

**Comment by zulh-civo** [comment]
> I was thinking should we add samples as well? Like if you run this it will look like this? 
> 
> In other words demo ? 

You mean, video demo? GIF?

**Comment by zulh-civo** [comment]
@saiyam1814 - I personally think we shouldn't include any demos in the docs as it will make it look longer and complex. It will add more clutters and make it hard for our users to navigate around to find what they need.

If we want to show demos, I'd like to suggest we do it via Civo Academy (video courses) — showing users (especially Terraform newbies) step-by-step what Terraform is, the use cases and how it can be used to manage cloud resources in Civo.

**Comment by saiyam1814** [comment]
Not the video demo, Just the files once you do terraform apply what gets created. something people can see that it actually works.

**Review by alejandrojnm — APPROVED** [review]

**Comment by zulh-civo** [comment]
@andyjeffries - what's your thoughts? Should we add Terraform state file samples in every Resource documentation page?

**Comment by zulh-civo** [comment]
In line with the latest discussion we had internally at Civo around "documenting Terraform provider docs", we agreed to make use of [tfplugindocs](https://github.com/hashicorp/terraform-plugin-docs) moving forward to help us generate Markdown docs from the provider's code and Terraform configuration [examples](https://github.com/hashicorp/terraform-plugin-docs#conventional-paths). It's also a [recommended](https://www.terraform.io/docs/registry/providers/docs.html#generating-documentation) way for docs generation.

This #79 contains docs update that were made manually and not via tfplugindocs tool. I'm going to close this PR and start using tfplugindocs tool. The new PR for this is #92.

Few other related points which I think worth noting here are:

* We will have a dedicated section on Civo.com website for Terraform users - especially newbies. The docs in this repo and Terraform Registry will remain for experienced users.
* Since there are certain conventions to follow when using tfplugindocs, we can't simply add extra sections in our docs (something like [this](https://github.com/civo/terraform-provider-civo/blob/8d2f4c5b7412cb8c1ff5f4109f48914799a0da34/docs/resources/kubernetes_cluster.md#node-sizes)) because it will get deleted/replaced when the tool runs.
* With that said, when PR 92 is merged, non-related sections will get deleted from the [docs](https://github.com/civo/terraform-provider-civo/tree/master/docs), as well as from Terraform Registry page. We _may_ place those extra stuffs somewhere else (probably in this repo too, or as a new page on Civo.com website).
* We haven't add tfplugindocs integration as part of our GitHub Actions/CI pipeline. The release process now is still manual (lead by @alejandrojnm). Moving forward, we'd like to add tfplugindocs as one of the step in our CI pipeline so contributors won't have to worry about writing docs. The CI will take care of it.
* With that said, every contributor is required to _manually_ run the tfplugindocs tool now before making a PR. Once we have the CI for tfplugindocs and release workflow in-place, the requirement can be dropped.

**Pull request closed without merging**
