### PR TITLE
fix: remove unnecessary retries and improve error handling

### LINKED ISSUE #263: [BUG] Using a wrong cidr_v4 does not get validated
## Issues

Using a completely wrong `cidr_v4` causes terraform to keep trying to provision this resource for two minutes rather than failing straight away:

```hcl
resource "civo_network" "volume-issue" {
  label = "blah-network"
  cidr_v4 = "sfdsdfsdf"

}
```

image

This should fail straight away as it does on the API, CLI, etc.

## Acceptance Criteria

* Have this resource fail straight away when entering the wrong value. 

This ticket should be used as a reference for a bigger piece of work revamping the way we handle errors in terraform. The default behaviour with our provider seems to be to keep trying and it does NOT return the error the API gives, which is a problem.

We need to go through the entire provider and change the behaviour for everything not by writing error messages in terraform provider, but returning errors from the API

### PR DESCRIPTION
**Pull request by Praveen005**
This PR fixes #263 
Fixes: #256
fixes: #269 
fixes: #271 
fixes: #273 
fixes: #270

Now we directly return the error received from the API, instead of retrying.

I have also added functions to parse the error received and return only the error code and associated message to the user.

It also fixes issues: 256, 249, 269, 271, 273.

This will likely fix 270 as well.

Screenshots from the Result:

Issue 263:

Screenshot 2024-07-22 215418

Issue 256:

Screenshot 2024-07-22 215753

Issue 249:

Screenshot 2024-07-22 220013

Issue 269:

Screenshot 2024-07-22 220222

Issue 271:

Screenshot 2024-07-22 220433

Issue 273:

Screenshot 2024-07-22 222247

### CODE REVIEW

**Review by uzaxirr — APPROVED** [review]

**Comment by uzaxirr** [comment]
Amazing work, thank you for the PR

**Comment by Praveen005** [comment]
Thank you @uzaxirr! Looking forward to contributing more.

**Comment by fernando-villalba** [comment]
@Praveen005 really amazing work! Thank you so much!

**Comment by Praveen005** [comment]
Thank you @fernando-villalba.

**Pull request merged**
