### PR TITLE
Add Labels and Taints to Node Pool configurations

### PR DESCRIPTION
**Pull request by uzaxirr**

### CODE REVIEW

**Comment by alejandrojnm** [comment]
@uzaxirr Do you test this ???

**Comment by uzaxirr** [comment]
> @uzaxirr Do you test this ???

Its still WIP

**Comment by uzaxirr** [comment]
TF provider Binary Log: https://app.warp.dev/block/MX0ttzM8NqBwIBeULGYZZ8

Screenshot 2024-03-20 at 12 40 17 AM


I used the below terraform file for testing purpose

```
data "civo_size" "xsmall" {
  filter {
    key = "type"
    values = ["kubernetes"]
  }

  sort {
    key = "ram"
    direction = "asc"
  }
}

resource "civo_kubernetes_cluster" "cluster" {
  name              = "uzairTestCLuster"
  cluster_type      = "k3s"
  applications      = ""
  region            = "NYC1"
  firewall_id       = ""
  pools {
    label      = "my-label"
    size = element(data.civo_size.xsmall.sizes, 0).name
    labels = {
      "uzair" = "rockstar"
    }
    node_count = 3
    taint {
      key    = "mykeyyy"
      value  = "valuerty"
      effect = "NoSchedule"
    }

  }
}

data "civo_kubernetes_cluster" "cluster" {
  name = civo_kubernetes_cluster.cluster.name
}
```

**Review by alejandrojnm — APPROVED** [review]
LGTM

**Pull request merged**
